### ISSUE TITLE
Chicken with no head, potential enemy

### ISSUE THREAD

**Issue by kolbaba** [brethash/klbb#9]
We could implement this guy as an enemy: https://avatars.githubusercontent.com/u/3298804?v=4

**Comment by brethash** [comment]
@kolbaba can you make this into a spritesheet like [this one](https://github.com/brethash/klbb/blob/main/assets/dude.png)? ❤️

**Comment by brethash** [comment]
Would be cool to do a randomizer to make it sporadically change direction!

**Comment by brethash** [comment]
And with the new background, it'd be funny to have them spawn from the door in the apple.

**Comment by kolbaba** [comment]
Created new issue for development/behavior of the chicken of head
